# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConsultaRepositorios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConsultaRepositorios
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'SnapKit'
  
  target 'ConsultaRepositoriosTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

  target 'ConsultaRepositoriosUITests' do
    # Pods for testing
  end

end
